### ISSUE TITLE
configurable-http-proxy start-up and /etc/hosts

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-uiserver#52]
On my Centos host:
```
$ hostname
drugs-and-money

$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

Jupyterhub hangs trying to start configurable-http-proxy, and connecting to localhost:8000 gives 404:
```
(venv) [oliverh@drugs-and-money cylc-uiserver]$ jupyterhub
[I 2019-06-27 16:49:28.516 JupyterHub app:2120] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.0.0
[I 2019-06-27 16:49:28.516 JupyterHub app:2120] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.0
[I 2019-06-27 16:49:28.517 JupyterHub app:1257] Loading cookie_secret from /home/oliverh/cylc/cylc-uiserver/jupyterhub_cookie_secret
[I 2019-06-27 16:49:28.531 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2019-06-27 16:49:28.532 JupyterHub app:1532] No admin users, admin interface will be unavailable.
[W 2019-06-27 16:49:28.532 JupyterHub app:1534] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2019-06-27 16:49:28.532 JupyterHub app:1563] Not using whitelist. Any authenticated user will be allowed.
[I 2019-06-27 16:49:28.560 JupyterHub app:2337] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-06-27 16:49:28.560 JupyterHub proxy:516] Found proxy pid file: /home/oliverh/cylc/cylc-uiserver/jupyterhub-proxy.pid
[W 2019-06-27 16:49:28.560 JupyterHub proxy:528] Proxy no longer running at pid=17430
[W 2019-06-27 16:49:28.561 JupyterHub proxy:642] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2019-06-27 16:49:28.561 JupyterHub proxy:645] Starting proxy @ http://:8000
16:49:28.698 [ConfigProxy] info: Proxying http://*:8000 to (no default)
16:49:28.700 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes

16:49:40.873 [ConfigProxy] error: 404 GET / 
```

**The Fix** (not understood): add one line to `/etc/hosts`:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
127.0.0.1   drugs-and-money
```

We should understand and document this.

**Comment by kinow** [comment]
Related issue in jupyterhub: https://github.com/jupyterhub/jupyterhub/issues/1918

**Comment by kinow** [comment]
@hjoliver nothing can be done in `cylc-uiserver`, or even in `jupyterhub/jupyterhub`. Should we resolve this issue by adding a note under a section like "Known Issues" somewhere in this project's Wiki, or README.md, or cylc-doc?

**Comment by hjoliver** [comment]
You might be right that nothing can be done as such, but presumably we should be able to understand why it causes a problem?

**Comment by kinow** [comment]
> presumably we should be able to understand why it causes a problem?

Fair enough, this might end up becoming a nice addition to the JupyterHub documentation too, they have a nice [Troubleshooting](https://jupyterhub.readthedocs.io/en/stable/troubleshooting.html) section where this info would fit well IMO.

**Comment by kinow** [comment]
FTR @oliver-sanders had an issue today where he could log in, but then "`/hup/spawn/` (or any other page for that matter) redirects back to `hub/login`". Solved by editing the `/etc/hosts` too.

**Comment by oliver-sanders** [comment]
Anything we need to do or document at the Cylc end?

**Comment by hjoliver** [comment]
Unfortunately I still don't really understand what caused the problem or why the fix worked.

**Comment by oliver-sanders** [comment]
Fixed with more recent versions?

**Comment by hjoliver** [comment]
Yep, tested fine with the unaltered /etc/hosts :tada:
